spring:
  thymeleaf:
    mode:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgres://drzwvebrbarwhl:075fab42800887cd863f50d03bb5baf5fa388f9937a2570494d70efd1389ac11@ec2-50-19-218-160.compute-1.amazonaws.com:5432/db5iuctlt9kbim


url:
  callback: https://spotifygen.herokuapp.com/callback

app:
  client:
    id: d3f10ce3616049e0bddd86f9d3051af0
    secret: b546a60532c14634be9f6b306bbda46b